# Form implementation generated from reading ui file 'Todo.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TodoList(object):
    def setupUi(self, TodoList):
        TodoList.setObjectName("TodoList")
        TodoList.resize(524, 353)
        self.label = QtWidgets.QLabel(parent=TodoList)
        self.label.setGeometry(QtCore.QRect(40, 10, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.list = QtWidgets.QListWidget(parent=TodoList)
        self.list.setGeometry(QtCore.QRect(210, 50, 291, 271))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.list.setFont(font)
        self.list.setObjectName("list")
        self.addButton = QtWidgets.QPushButton(parent=TodoList)
        self.addButton.setGeometry(QtCore.QRect(40, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(parent=TodoList)
        self.deleteButton.setGeometry(QtCore.QRect(40, 250, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.txtBox = QtWidgets.QLineEdit(parent=TodoList)
        self.txtBox.setGeometry(QtCore.QRect(40, 100, 131, 31))
        self.txtBox.setObjectName("txtBox")

        self.retranslateUi(TodoList)
        QtCore.QMetaObject.connectSlotsByName(TodoList)

    def retranslateUi(self, TodoList):
        _translate = QtCore.QCoreApplication.translate
        TodoList.setWindowTitle(_translate("TodoList", "TodoList"))
        self.label.setText(_translate("TodoList", "To-do 🎀"))
        self.addButton.setText(_translate("TodoList", "Add"))
        self.deleteButton.setText(_translate("TodoList", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TodoList = QtWidgets.QDialog()
    ui = Ui_TodoList()
    ui.setupUi(TodoList)
    TodoList.show()
    sys.exit(app.exec())
